### ISSUE TITLE
@OnGroupMemberIncrease注解无效

### ISSUE THREAD

**Issue by vvzzxd3** [ForteScarlet/simple-robot-component-mirai#4]
component-mirai:1.1.0-1.16
监听函数加载成功
用户成功进入群之后，并未触发成员增加事件。

**Comment by ForteScarlet** [comment]
这似乎是mirai导致的，机器人同意申请后便不会再触发新成员入群事件。
此问题暂时观望mirai后续更新，暂且不做处理。
